// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO Transaction (reciever_id, sender_id, currency, amount, message, deadline)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, reciever_id, sender_id, amount, currency, message, deadline, created_at
`

type CreateTransactionParams struct {
	RecieverID int64
	SenderID   int64
	Currency   string
	Amount     int64
	Message    sql.NullString
	Deadline   sql.NullTime
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.RecieverID,
		arg.SenderID,
		arg.Currency,
		arg.Amount,
		arg.Message,
		arg.Deadline,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.RecieverID,
		&i.SenderID,
		&i.Amount,
		&i.Currency,
		&i.Message,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM Transaction WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getAmountTransactions = `-- name: GetAmountTransactions :many
SELECT id, reciever_id, sender_id, amount, currency, message, deadline, created_at FROM Transaction WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAmountTransactions(ctx context.Context, id int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAmountTransactions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.RecieverID,
			&i.SenderID,
			&i.Amount,
			&i.Currency,
			&i.Message,
			&i.Deadline,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const giveAmountTransactions = `-- name: GiveAmountTransactions :many
SELECT id, reciever_id, sender_id, amount, currency, message, deadline, created_at FROM Transaction WHERE reciever_id = $1 LIMIT 1
`

func (q *Queries) GiveAmountTransactions(ctx context.Context, recieverID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, giveAmountTransactions, recieverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.RecieverID,
			&i.SenderID,
			&i.Amount,
			&i.Currency,
			&i.Message,
			&i.Deadline,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeadline = `-- name: UpdateDeadline :exec
UPDATE Transaction SET deadline = $2 WHERE id = $1
`

type UpdateDeadlineParams struct {
	ID       int64
	Deadline sql.NullTime
}

func (q *Queries) UpdateDeadline(ctx context.Context, arg UpdateDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, updateDeadline, arg.ID, arg.Deadline)
	return err
}

const updateTranactionAmount = `-- name: UpdateTranactionAmount :exec
UPDATE Transaction SET amount = $2 WHERE id = $1
`

type UpdateTranactionAmountParams struct {
	ID     int64
	Amount int64
}

func (q *Queries) UpdateTranactionAmount(ctx context.Context, arg UpdateTranactionAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateTranactionAmount, arg.ID, arg.Amount)
	return err
}
